# tasks file for ubuntu-1804-letsencrypt
---
- name: configuration | copy configuration file
  template:
    src: etc/letsencrypt/cli.ini.j2
    dest: "/etc/letsencrypt/cli.ini"

- name: configuration | create http challenges directory
  file:
    path: "{{ ubuntu_1804_letsencrypt_webroot_path }}/{{ ubuntu_1804_letsencrypt_acme_challenge_path }}"
    state: directory

# - include: configuration-apache.yml

# - include: configuration-nginx.yml
